<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Moslashuvchan Sayt</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; background-color: #222; color: white; }
        .container { max-width: 600px; margin: auto; padding: 20px; background: #333; border-radius: 10px; }
        input, button { padding: 10px; width: 100%; margin-top: 10px; border: none; border-radius: 5px; }
        input { background: #444; color: white; }
        button { background: #008CBA; color: white; cursor: pointer; }
        #content { margin-top: 20px; padding: 10px; background-color: #444; border-radius: 5px; }
    </style>
</head>
<body>
    <div class="container">
        <h2>AI Moslashuvchan Sayt</h2>
        <p id="content">Bu sayt avtomatik ravishda yangilanadi!</p>
        
        <h3>🔄 Sayt kontentini o‘zgartirish</h3>
        <input type="text" id="newContent" placeholder="Yangi matnni kiriting...">
        <button onclick="updateContent()">Yangilash</button>

        <h3>🤖 AI bilan bog‘lanish</h3>
        <input type="text" id="aiInput" placeholder="AI ga savol bering...">
        <button onclick="askAI()">AI bilan suhbat</button>
        <p id="aiResponse"></p>
    </div>

    <script>
        function updateContent() {
            let newContent = document.getElementById("newContent").value;
            if (!newContent) return;
            document.getElementById("content").innerText = newContent;
        }

        async function askAI() {
            let userMessage = document.getElementById("aiInput").value;
            if (!userMessage) return;

            const response = await fetch("https://api.openai.com/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Authorization": Bearer YOUR_OPENAI_API_KEY,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    model: "gpt-4-turbo",
                    messages: [{ role: "user", content: userMessage }]
                })
            });

            const data = await response.json();
            document.getElementById("aiResponse").innerText = data.choices[0].message.content;
        }
    </script>
</body>
</html>
