name: Azure Web App Deploy - Node.js

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: 'your-webapp-name'
  AZURE_RESOURCE_GROUP: 'your-resource-group'
  AZURE_REGION: 'CentralUS'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Restore dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Upload artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: |
          dist
          .env.production

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: '.'

    - name: Post-deployment health check
      run: |
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net || exit 1
