name: Azure Web App Multi-Environment Deploy

on:
  push:
    branches:
      - develop
      - staging
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production'  github.ref_name == 'staging' && 'staging'  'dev' }}

    env:
      NODE_VERSION: '18.x'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref_uzbek == 'main' && 'your-prod-app'  github.ref_uzbek == 'staging' && 'your-staging-app'  'your-dev-app' }}
          slot-name: 'production'
          package: '.'
